#!/usr/bin/env node
/**
 * Print a SQL query that reports every column Prisma expects and the database
 * doesn't have.
 *
 *   node scripts/schema-drift.mjs | pbcopy     # then paste into the SQL editor
 *
 * Why this exists: migrations here are hand-run files in prisma/manual, so the
 * schema and the database drift apart silently and are only discovered when a
 * customer hits the gap. It has already happened once — a column added to a
 * model put itself into the RETURNING clause of every select-less write on that
 * table, and saving storefront settings started failing for everyone.
 *
 * Prisma returns ALL scalar columns when a query has no `select`, so a single
 * un-migrated column can break writes that never mention it. That makes "which
 * columns are missing" a question worth being able to ask in ten seconds.
 *
 * Run it after pulling, and before blaming the application for a save that
 * fails on one database and works on another.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = readFileSync(join(root, "prisma/schema.prisma"), "utf8");

const modelNames = new Set([...src.matchAll(/^model\s+(\w+)\s*\{/gm)].map((m) => m[1]));

/** table -> columns Prisma believes exist. */
const expected = new Map();

for (const m of src.matchAll(/^model\s+(\w+)\s*\{([\s\S]*?)^\}/gm)) {
  const [, model, body] = m;
  const table = body.match(/@@map\("([^"]+)"\)/)?.[1] ?? model;
  const columns = [];

  for (const raw of body.split("\n")) {
    const line = raw.split("//")[0].trim();
    if (!line || line.startsWith("@@")) continue;

    const field = line.match(/^(\w+)\s+(\w+)(\[\])?(\?)?(.*)$/);
    if (!field) continue;
    const [, name, type, isList, , rest] = field;

    // A list is the other side of a relation and a model-typed field is the
    // relation object itself. Neither is a column; only the scalar foreign key
    // beside them is, and that is declared separately.
    if (isList || modelNames.has(type)) continue;

    columns.push(rest.match(/@map\("([^"]+)"\)/)?.[1] ?? name);
  }
  expected.set(table, columns);
}

const values = [...expected]
  .flatMap(([t, cols]) => cols.map((c) => `('${t}','${c}')`))
  .join(",");

// Tables absent entirely are reported as a missing table rather than as one row
// per column, which would bury the real finding under fifty lines of noise.
process.stdout.write(`-- Generated by scripts/schema-drift.mjs. Read-only.
-- Expect zero rows. Anything returned is a migration in prisma/manual that
-- has not been run on this database.
WITH expected(t, c) AS (VALUES ${values}),
tables AS (
  SELECT DISTINCT t, to_regclass('public.' || quote_ident(t)) IS NOT NULL AS present FROM expected
)
SELECT 'MISSING TABLE' AS problem, t AS table_name, NULL AS column_name
FROM tables WHERE NOT present
UNION ALL
SELECT 'missing column', e.t, e.c
FROM expected e
JOIN tables tb ON tb.t = e.t AND tb.present
WHERE NOT EXISTS (
  SELECT 1 FROM information_schema.columns k
  WHERE k.table_schema = 'public' AND k.table_name = e.t AND k.column_name = e.c
)
ORDER BY 1, 2, 3;
`);
