import QRCode from "qrcode";

/**
 * Builds the diner URL a table's QR code points to:
 *   {APP_URL}/order/{slug}/{tableToken}
 * This is the exact route the diner lands on after scanning (Phase 1).
 */
export function dinerOrderUrl(slug: string, qrToken: string): string {
  const base = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  return `${base.replace(/\/$/, "")}/order/${slug}/${qrToken}`;
}

/**
 * The diner URL to encode in a table's QR. Prefers the restaurant's own
 * verified custom domain; otherwise uses the platform apex path
 * ({APP_URL}/order/{slug}/{token}), which works without wildcard-subdomain DNS.
 */
export function restaurantOrderUrl(
  r: {
    slug: string;
    subdomain?: string | null;
    customDomain?: string | null;
    customDomainVerified?: boolean;
  },
  qrToken: string,
): string {
  if (r.customDomain && r.customDomainVerified) {
    return `https://${r.customDomain}/t/${qrToken}`;
  }
  // Servd subdomains are disabled (no wildcard *.servdph.com DNS) — fall back to
  // the apex path so QR codes resolve on the main domain.
  return dinerOrderUrl(r.slug, qrToken);
}

/** The restaurant's online-ordering page: {APP_URL}/r/{slug}/order. */
export function restaurantSiteUrl(slug: string): string {
  const base = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  return `${base.replace(/\/$/, "")}/r/${slug}/order`;
}

/**
 * Renders a QR code as an inline SVG string. SVG (not PNG) so it stays crisp at
 * any print size. The result is injected via dangerouslySetInnerHTML in the
 * print sheet — safe because the content is generated by us, not user input.
 */
export function qrSvg(data: string): Promise<string> {
  return QRCode.toString(data, {
    type: "svg",
    errorCorrectionLevel: "M",
    margin: 1,
    width: 220,
  });
}

/**
 * Renders a QR code as a PNG data URL — handy for showing in an <img> and for a
 * one-click download/share (e.g. sending a demo storefront's QR to a customer).
 */
export function qrPngDataUrl(data: string): Promise<string> {
  return QRCode.toDataURL(data, {
    errorCorrectionLevel: "M",
    margin: 2,
    width: 512,
  });
}
