import Link from "next/link";
import { requireAdminPage } from "@/server/tenancy/require-admin";
import { getTables, getRestaurantBrief } from "@/server/tables/queries";
import { restaurantOrderUrl, qrSvg } from "@/lib/qr";
import { PrintButton } from "@/components/admin/PrintButton";

export default async function PrintTablesPage() {
  const { restaurantId } = await requireAdminPage();
  const [tables, restaurant] = await Promise.all([
    getTables(restaurantId),
    getRestaurantBrief(restaurantId),
  ]);

  // Generate one crisp SVG QR per table (server-side).
  const cards = await Promise.all(
    tables.map(async (t) => ({
      tableNumber: t.tableNumber,
      svg: await qrSvg(
        restaurantOrderUrl(
          {
            slug: restaurant.slug,
            subdomain: restaurant.subdomain,
            customDomain: restaurant.customDomain,
            customDomainVerified: !!restaurant.customDomainVerifiedAt,
          },
          t.qrToken,
        ),
      ),
    })),
  );

  const name = restaurant.displayName || restaurant.name;

  return (
    <div>
      <div className="mb-6 flex items-center justify-between print:hidden">
        <Link href="/admin/tables" className="text-sm text-plum-ink/50">
          ← Tables
        </Link>
        <PrintButton>Print sheet</PrintButton>
      </div>

      {/* Print grid: 2 per row, never split a card across pages. */}
      <div className="grid grid-cols-2 gap-4 print:gap-2">
        {cards.map((c) => (
          <div
            key={c.tableNumber}
            className="flex flex-col items-center rounded-tile border border-plum-ink/15 bg-white p-6 text-center [break-inside:avoid]"
          >
            <p className="font-heading text-lg font-extrabold">{name}</p>
            <p className="text-sm text-plum-ink/60">Scan to view menu &amp; order</p>
            <div
              className="my-4 h-[220px] w-[220px]"
              // Safe: SVG is generated by us from our own data, not user input.
              dangerouslySetInnerHTML={{ __html: c.svg }}
            />
            <p className="font-heading text-2xl font-extrabold">
              Table {c.tableNumber}
            </p>
          </div>
        ))}
      </div>

      {cards.length === 0 && (
        <p className="text-sm text-plum-ink/50">
          No tables to print yet.{" "}
          <Link href="/admin/tables" className="text-brand-primary">
            Add a table
          </Link>
          .
        </p>
      )}
    </div>
  );
}
