import "server-only";
import { pharmacyDb } from "@/server/tenancy/scoped-db";
import { checkDelivery, hasErrors, type DeliveryLine, type LineIssue } from "@/lib/pharmacy/receiving";

/**
 * Record a delivery.
 *
 * ONE transaction. A delivery that half-lands is worse than one that fails:
 * the batches would be on the shelf with no movements explaining them, and the
 * stock ledger is the thing a regulator asks for.
 *
 * EVERY LINE IS A NEW BATCH ROW, even when the lot number matches one already
 * on hand. Two deliveries are two deliveries: they can carry different costs,
 * and FEFO breaks ties on received date. Merging them would flatten both, and
 * the margin on the older one would quietly become the newer one's.
 *
 * Scoped through pharmacyDb, so a productId belonging to another pharmacy is
 * not found rather than received into.
 */

export interface ReceiveDeliveryInput {
  pharmacyId: string;
  actorStaffId: string;
  /** Generated by the form. The idempotency key — see below. */
  deliveryRef: string;
  supplierId?: string | null;
  /**
   * Which branch the boxes were delivered to. From the session, never the
   * form. Null is read as the main branch.
   */
  branchId?: string | null;
  /** Set to create a supplier as part of the delivery. */
  newSupplierName?: string;
  lines: DeliveryLine[];
  /** Whether this caller may create products, not just receive into them. */
  canCreateProducts: boolean;
  reference?: string;
  asOf?: Date;
}

export type ReceiveFailure =
  | "no_lines"
  | "invalid"
  | "unknown_product"
  | "needs_catalogue_permission"
  | "already_received";

export type ReceiveOutcome =
  | { ok: true; batchesCreated: number; unitsReceived: number; issues: LineIssue[] }
  | { ok: false; reason: ReceiveFailure; message: string; issues?: LineIssue[] };

export async function receiveDelivery(
  input: ReceiveDeliveryInput,
): Promise<ReceiveOutcome> {
  const lines = input.lines;
  if (lines.length === 0) {
    return { ok: false, reason: "no_lines", message: "Nothing to receive." };
  }

  const issues = checkDelivery(lines, input.asOf ?? new Date());
  if (hasErrors(issues)) {
    return {
      ok: false,
      reason: "invalid",
      message: "Some lines need fixing before this can be received.",
      issues,
    };
  }

  const creating = lines.filter((l) => !l.productId);
  if (creating.length > 0 && !input.canCreateProducts) {
    // A pharmacist may receive stock; pricing a product that has never been
    // sold here is a catalogue decision, and the price is what the till will
    // charge. Manager or owner.
    return {
      ok: false,
      reason: "needs_catalogue_permission",
      message:
        `${creating.length} line${creating.length === 1 ? " is" : "s are"} a new product. ` +
        "Adding one to the catalogue needs a manager or the owner — a pharmacist can receive stock into products that already exist.",
    };
  }

  return pharmacyDb(input.pharmacyId, async (tx) => {
    // Idempotency. A slow connection and an impatient second click would
    // otherwise double the stock on the shelf, and nothing downstream would
    // ever notice — the batches and the movements would both be internally
    // consistent, just twice.
    const seen = await tx.pharmacyStockMovement.findFirst({
      where: { referenceId: input.deliveryRef, type: "receive" },
      select: { id: true },
    });
    if (seen) {
      return {
        ok: false,
        reason: "already_received",
        message: "That delivery has already been recorded.",
      };
    }

    // Verify every named product belongs to THIS pharmacy. Under RLS a
    // foreign id simply is not found, which is the answer we want — but it has
    // to be checked before anything is written, not discovered by a foreign-key
    // error halfway through.
    const namedIds = lines.map((l) => l.productId).filter((id): id is string => !!id);
    if (namedIds.length > 0) {
      const found = await tx.pharmacyProduct.findMany({
        where: { id: { in: namedIds } },
        select: { id: true },
      });
      if (found.length !== new Set(namedIds).size) {
        return {
          ok: false,
          reason: "unknown_product",
          message: "One of those products isn't in this pharmacy's catalogue.",
        };
      }
    }

    let supplierId = input.supplierId || null;
    if (!supplierId && input.newSupplierName?.trim()) {
      const supplier = await tx.pharmacySupplier.create({
        data: { pharmacyId: input.pharmacyId, name: input.newSupplierName.trim() },
        select: { id: true },
      });
      supplierId = supplier.id;
    }

    let batchesCreated = 0;
    let unitsReceived = 0;

    for (const line of lines) {
      let productId = line.productId;

      if (!productId) {
        const created = await tx.pharmacyProduct.create({
          data: {
            pharmacyId: input.pharmacyId,
            name: line.newProductName!.trim(),
            priceCentavos: line.newProductPriceCentavos!,
          },
          select: { id: true },
        });
        productId = created.id;
      }

      const batch = await tx.pharmacyBatch.create({
        data: {
          pharmacyId: input.pharmacyId,
          productId,
          supplierId,
          lotNumber: line.lotNumber?.trim() || null,
          expiryDate: line.expiryDate ? new Date(`${line.expiryDate.slice(0, 10)}T00:00:00Z`) : null,
          quantity: line.quantity,
          costCentavos: line.unitCostCentavos,
          branchId: input.branchId ?? null,
        },
        select: { id: true },
      });

      await tx.pharmacyStockMovement.create({
        data: {
          pharmacyId: input.pharmacyId,
          productId,
          batchId: batch.id,
          type: "receive",
          quantityDelta: line.quantity,
          // The whole delivery shares one reference, which is what makes the
          // idempotency check above possible and what lets the ledger be read
          // back as a delivery rather than as N unrelated movements.
          referenceId: input.deliveryRef,
          reason: input.reference?.trim()
            ? `Delivery ${input.reference.trim()}`
            : "Delivery received",
          actorStaffId: input.actorStaffId,
          branchId: input.branchId ?? null,
        },
      });

      batchesCreated += 1;
      unitsReceived += line.quantity;
    }

    return { ok: true, batchesCreated, unitsReceived, issues };
  });
}

/** Products and suppliers the receiving form needs to offer. */
export async function receivingOptions(pharmacyId: string) {
  return pharmacyDb(pharmacyId, async (tx) => {
    const [products, suppliers] = await Promise.all([
      tx.pharmacyProduct.findMany({
        where: { isActive: true },
        orderBy: { name: "asc" },
        select: { id: true, name: true, genericName: true, unit: true },
      }),
      tx.pharmacySupplier.findMany({
        orderBy: { name: "asc" },
        select: { id: true, name: true },
      }),
    ]);
    return { products, suppliers };
  });
}

/** Recent deliveries, newest first — grouped by the reference they share. */
export async function recentDeliveries(pharmacyId: string, take = 40) {
  const movements = await pharmacyDb(pharmacyId, (tx) =>
    tx.pharmacyStockMovement.findMany({
      where: { type: "receive" },
      orderBy: { createdAt: "desc" },
      take,
      select: {
        referenceId: true,
        quantityDelta: true,
        reason: true,
        createdAt: true,
        product: { select: { name: true } },
        batch: { select: { lotNumber: true, expiryDate: true, costCentavos: true } },
      },
    }),
  );

  const byRef = new Map<
    string,
    {
      ref: string;
      at: Date;
      reason: string | null;
      lines: {
        product: string;
        quantity: number;
        lotNumber: string | null;
        expiryDate: Date | null;
        costCentavos: number;
      }[];
    }
  >();

  for (const m of movements) {
    const ref = m.referenceId ?? m.createdAt.toISOString();
    const entry = byRef.get(ref) ?? {
      ref,
      at: m.createdAt,
      reason: m.reason,
      lines: [],
    };
    entry.lines.push({
      product: m.product.name,
      quantity: m.quantityDelta,
      lotNumber: m.batch?.lotNumber ?? null,
      expiryDate: m.batch?.expiryDate ?? null,
      costCentavos: m.batch?.costCentavos ?? 0,
    });
    byRef.set(ref, entry);
  }

  return [...byRef.values()];
}
